trigger: 
- master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: marketplace-publish-vars

stages:
#   - stage: Run_and_publish_unit_tests
#     jobs:
#       - job:
#         steps:
#           - task: NodeTool@0
#             displayName: 'Use Node 12.18.4'
#             inputs:
#               versionSpec: 12.18.4
#           - task: TfxInstaller@3
#             inputs:
#               version: "v0.7.x"
#           - task: Npm@1
#             inputs:
#               command: 'install'
#               workingDir: 'buildAndReleaseTask'
#           - task: Bash@3
#             displayName: Compile Javascript
#             inputs:
#               targetType: "inline"
#               script: |
#                 cd buildAndReleaseTask
#                 tsc
#           - task: Npm@1
#             inputs:
#               command: 'custom'
#               workingDir: 'buildAndReleaseTask'
#               customCommand: 'test'
#           - task: PublishTestResults@2
#             inputs:
#               testResultsFormat: 'JUnit'
#               testResultsFiles: '**/ResultsFile.xml'
  - stage: Package_extension_and_publish_build_artifacts
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 12.18.4'
            inputs:
              versionSpec: 12.18.4
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'buildAndReleaseTask'
          - task: Bash@3
            displayName: Compile Javascript
            inputs:
              targetType: "inline"
              script: |
                cd buildAndReleaseTask
                tsc
          - task: QueryAzureDevOpsExtensionVersion@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(connectedServiceName)'
              publisherId: '$(PublisherID)'
              extensionId: 'dm-azure-doppler'
              versionAction: 'Patch'
              outputVariable: 'Task.Extension.Version'
          - task: PackageAzureDevOpsExtension@3
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)'
              publisherId: '$(PublisherID)'
              extensionId: 'dm-azure-doppler'
              extensionName: 'Digital Makers - Doppler Setup'
              extensionVersion: '$(Task.Extension.Version)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: 'private' 
              extensionPricing: 'free'
          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
            inputs:
              Contents: "**/*.vsix"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'dm-doppler'
              publishLocation: 'Container'
  - stage: Download_build_artifacts_and_publish_the_extension
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 12.18.4'
            inputs:
              versionSpec: 12.18.4
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "dm-doppler"
              downloadPath: "$(System.DefaultWorkingDirectory)"
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(connectedServiceName)' 
              fileType: 'vsix'
              vsixFile: '**/*.vsix'
              publisherId: '$(PublisherID)'
              extensionId: 'dm-azure-doppler'
              extensionName: 'Digital Makers - Doppler Setup'
              updateTasksVersion: false
              extensionVisibility: 'private' 
              extensionPricing: 'free'